name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/2 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit app
        run: |
          status=$(curl \
          --silent \
          --location \
          --max-redirs 10 \
          --output /dev/null \
          --write-out "%{http_code}" \
          https://osr-fatec.streamlit.app)

          echo "Status: $status"

          if [ "$status" != "200" ]; then
            echo "Aplicação respondeu com código inesperado"
            exit 1
          fi
